#!/usr/bin/env python3
"""
scripts/figures/extract_paper_macros.py
=======================================
Reads the on-disk experiment outputs and writes one ``results.tex``
per paper containing all headline numbers as ``\\newcommand`` macros.
The papers ``\\input{results.tex}`` so that every numerical claim is
sourced from a single audited file --- there are no hard-coded
numbers in the .tex body.

Sources read (all real-data files produced by the campaign scripts):
  * gridpilot/data/v100_raw/headline_table.csv
    (E1 best-efficiency operating point + AR(4) MAE; written by
    scripts/v100/aggregate_headline.py)
  * gridpilot/data/v100_raw/E7_ffr_latency/verdict.json
    (E7 end-to-end FR-actuation latency; written by
    scripts/v100/experiments/run_e7_ffr_latency.py)
  * gridpilot/data/m100/country_sweep/COUNTRY_SUMMARY.csv
    (multi-country f-SLA + PUE-aware sweep; written by
    scripts/multicountry/replay_country_sweep.py OR by the stub
    seed_country_sweep_stub.py --- the stub case is FLAGGED in the
    macro file's banner so the paper can render a warning)
  * gridpilot/data/m100/policy_matrix/HYPOTHESIS_OUTCOMES.json
    (PECS Finding 4 H1--H5 acceptance flags)

Data-provenance flag
--------------------
``results.tex`` includes a single boolean macro \\StubDataPresent
that the papers can `\\if` on to render a banner.  This makes the
stub-vs-real distinction visible in the rendered PDF, satisfying
the integrity requirement that no headline number be presented as
real measurement when it actually comes from a literature-anchored
placeholder.

Run as:
    PYTHONPATH=src python scripts/figures/extract_paper_macros.py
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parents[2]


def _fmt(v: float, n: int = 2) -> str:
    """Format a float for LaTeX without trailing scientific notation."""
    return f"{v:.{n}f}"


def _macro(name: str, value: str) -> str:
    """One \\newcommand line, escaped for LaTeX."""
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


# ─────────────────────────────────────────────────────────────────────
# WHPC: V100 hardware measurements (REAL)
# ─────────────────────────────────────────────────────────────────────
def whpc_macros() -> tuple[str, bool, list[str]]:
    """Emit the WHPC macro block.  Returns (text, is_stub, missing)."""
    missing: list[str] = []
    out = ["% --- WHPC headline measurements ----------------------\n",
            "% Generated by extract_paper_macros.py.  Source files:\n",
            "%   data/v100_raw/E7_ffr_latency/verdict.json\n",
            "%   data/v100_raw/headline_table.csv\n",
            "% Do NOT edit by hand --- re-run the extractor instead.\n"]

    # ── E7: end-to-end FR actuation latency
    e7_path = ROOT / "data" / "v100_raw" / "E7_ffr_latency" / "verdict.json"
    if not e7_path.exists():
        missing.append(str(e7_path.relative_to(ROOT)))
        # Sensible placeholders so the build does not break
        out += [_macro("WhpcMedMatmul", "?"),
                _macro("WhpcMedInfer",  "?"),
                _macro("WhpcMedBursty", "?"),
                _macro("WhpcMaxOverall","?"),
                _macro("WhpcPassRate",  "?/?")]
    else:
        v = json.loads(e7_path.read_text())
        per = v["per_workload"]
        med_mat = per["matmul_compute_bound"]["median_ms"]
        med_inf = per["inference_memory_bound"]["median_ms"]
        med_brs = per["bursty_alternating"]["median_ms"]
        max_all = max(per[k]["max_ms"] for k in per)
        n_pass = sum(per[k]["n_pass"] for k in per)
        n_trial = sum(per[k]["n_trials"] for k in per)
        budget_ms = v["budget_ms"]
        margin = budget_ms / max_all
        out += [_macro("WhpcMedMatmul", _fmt(med_mat, 1)),
                _macro("WhpcMedInfer",  _fmt(med_inf, 1)),
                _macro("WhpcMedBursty", _fmt(med_brs, 1)),
                _macro("WhpcMaxOverall",_fmt(max_all, 1)),
                _macro("WhpcPassRate",  f"{n_pass}/{n_trial}"),
                _macro("WhpcBudgetMs",  str(int(budget_ms))),
                _macro("WhpcMarginX",   _fmt(margin, 1))]

    # ── E1/E3 headline table
    head_path = ROOT / "data" / "v100_raw" / "headline_table.csv"
    if not head_path.exists():
        missing.append(str(head_path.relative_to(ROOT)))
        out += [_macro("WhpcIPJInfer",  "?"),
                _macro("WhpcIPJMatmul", "?"),
                _macro("WhpcIPJBursty", "?"),
                _macro("WhpcMAEinfer",  "?"),
                _macro("WhpcMAEmatmul", "?"),
                _macro("WhpcMAEbursty", "?")]
    else:
        rows = list(csv.DictReader(head_path.open()))
        def _pick(workload: str, metric: str) -> Optional[float]:
            for r in rows:
                if r["workload"] == workload and r["metric"] == metric:
                    return float(r["value"])
            return None
        ipj_i = _pick("inference_memory_bound", "best_efficiency_iters_per_joule")
        ipj_m = _pick("matmul_compute_bound",   "best_efficiency_iters_per_joule")
        ipj_b = _pick("bursty_alternating",     "best_efficiency_iters_per_joule")
        mae_i = _pick("inference_memory_bound", "ar4_mae_w")
        mae_m = _pick("matmul_compute_bound",   "ar4_mae_w")
        mae_b = _pick("bursty_alternating",     "ar4_mae_w")
        out += [_macro("WhpcIPJInfer",  _fmt(ipj_i, 3) if ipj_i else "?"),
                _macro("WhpcIPJMatmul", _fmt(ipj_m, 3) if ipj_m else "?"),
                _macro("WhpcIPJBursty", _fmt(ipj_b, 3) if ipj_b else "?"),
                _macro("WhpcMAEinfer",  _fmt(mae_i, 2) if mae_i else "?"),
                _macro("WhpcMAEmatmul", _fmt(mae_m, 2) if mae_m else "?"),
                _macro("WhpcMAEbursty", _fmt(mae_b, 2) if mae_b else "?")]

    # WHPC is always real-measured (the V100 testbed campaign is what
    # the user ran on EPFL EcoCloud); no stub fallback.
    return "".join(out), False, missing


# ─────────────────────────────────────────────────────────────────────
# PECS: multi-country sweep (stub OR real --- flagged explicitly)
# ─────────────────────────────────────────────────────────────────────
COUNTRIES = ["SE", "CH", "FR", "IT", "DE", "PL"]
MW_HEADLINE = 10.0   # paper headline scale
M_LEAD = "M3"        # AI-Baseline Audit mechanism


def pecs_macros() -> tuple[str, bool, list[str]]:
    missing: list[str] = []
    is_stub = False
    out = ["% --- PECS multi-country headline ---------------------\n",
            "% Generated by extract_paper_macros.py.  Source files:\n",
            "%   data/m100/country_sweep/COUNTRY_SUMMARY.csv\n",
            "%   data/m100/policy_matrix/HYPOTHESIS_OUTCOMES.json\n",
            "% \\StubDataPresent below is true iff the COUNTRY_SUMMARY\n",
            "% comes from the literature-anchored stub rather than a\n",
            "% real replay_country_sweep.py run.\n"]

    summary_path = ROOT / "data" / "m100" / "country_sweep" / "COUNTRY_SUMMARY.csv"
    manifest_path = ROOT / "data" / "m100" / "country_sweep" / "RUN_MANIFEST.json"

    # Provenance detection: the stub does NOT write RUN_MANIFEST.json,
    # the real driver does.  If the manifest is missing, we treat the
    # summary as stub-derived.
    if summary_path.exists() and manifest_path.exists():
        is_stub = False
    elif summary_path.exists():
        is_stub = True
    else:
        missing.append(str(summary_path.relative_to(ROOT)))
        is_stub = True

    out.append(_macro("StubDataPresent", "true" if is_stub else "false"))

    if not summary_path.exists():
        # Emit ?'s so the LaTeX still compiles
        for c in COUNTRIES:
            out += [_macro(f"PecsCfeLift{c}",      "?"),
                    _macro(f"PecsBaseCfe{c}",      "?"),
                    _macro(f"PecsFslaCfe{c}",      "?"),
                    _macro(f"PecsAvoidedT{c}",     "?")]
    else:
        rows = list(csv.DictReader(summary_path.open()))
        def _lookup(country: str, mw: float, layer: str, mech: str,
                     field: str) -> Optional[float]:
            for r in rows:
                try:
                    if (r["country"] == country
                            and abs(float(r["mw"]) - mw) < 1e-6
                            and r["layer"] == layer
                            and r["mechanism"] == mech):
                        return float(r[field])
                except (KeyError, ValueError):
                    continue
            return None

        # Demand flexibility at MW_HEADLINE (10 MW): GWh/y of compute
        # energy that f-SLA elicitation makes movable, computed as
        # (Delta CFE pp / 100) x MW_HEADLINE x 8760 h/y.
        ANNUAL_GWH_PER_MW = 8.76
        # Prefer the absolute CFE metric (energy below 150 g/kWh)
        # when present --- it discriminates between grids whereas the
        # per-country-normalised metric saturates around 50 %.
        # Falls back to the normalised metric if cfe_abs_* columns
        # are missing (older sweep CSVs).
        def _pref(c: str, layer_: str, mech: str, abs_field: str,
                   pct_field: str) -> Optional[float]:
            v = _lookup(c, MW_HEADLINE, layer_, mech, abs_field)
            if v is not None:
                return v
            return _lookup(c, MW_HEADLINE, layer_, mech, pct_field)

        for c in COUNTRIES:
            lift  = _pref(c, "fsla", M_LEAD, "cfe_abs_lift_pp_mean", "cfe_lift_pp_mean")
            base  = _pref(c, "fsla", "none", "cfe_abs_pct_mean",     "cfe_pct_mean")
            full  = _pref(c, "fsla", M_LEAD, "cfe_abs_pct_mean",     "cfe_pct_mean")
            avoid = _lookup(c, 50.0, "fsla", M_LEAD, "co2_avoided_t_y_mean")
            # avoided tonnage reported at 50 MW for impact context
            avoid_kt = (avoid / 1000.0) if avoid is not None else None
            # demand flexibility (GWh/y) at MW_HEADLINE IT
            flex_gwh = (lift / 100.0 * MW_HEADLINE * ANNUAL_GWH_PER_MW
                        if lift is not None else None)
            # CI-weighted-mean metric (g CO2eq/kWh): the effective
            # grid CI the cluster ran on.  Baseline = no-f-SLA, FSLA
            # = M3 audit; lift = baseline - fsla (positive => contract
            # shifted compute to cleaner hours, in g/kWh).  This
            # metric ranks grids correctly (SE ~11, PL ~612) and has
            # continuous dynamic range.
            ciwm_base = _lookup(c, MW_HEADLINE, "fsla", "none", "ci_weighted_mean_g")
            ciwm_full = _lookup(c, MW_HEADLINE, "fsla", M_LEAD, "ci_weighted_mean_g")
            ciwm_lift = _lookup(c, MW_HEADLINE, "fsla", M_LEAD, "ci_weighted_lift_g_mean")
            out += [_macro(f"PecsCfeLift{c}",  _fmt(lift,    1) if lift is not None     else "?"),
                    _macro(f"PecsBaseCfe{c}",  _fmt(base,    1) if base is not None     else "?"),
                    _macro(f"PecsFslaCfe{c}",  _fmt(full,    1) if full is not None     else "?"),
                    _macro(f"PecsAvoidedT{c}", _fmt(avoid_kt,1) if avoid_kt is not None else "?"),
                    _macro(f"PecsFlexGWh{c}",  _fmt(flex_gwh,1) if flex_gwh is not None else "?"),
                    _macro(f"PecsCiBase{c}",   _fmt(ciwm_base,0) if ciwm_base is not None else "?"),
                    _macro(f"PecsCiFsla{c}",   _fmt(ciwm_full,0) if ciwm_full is not None else "?"),
                    _macro(f"PecsCiLift{c}",   _fmt(ciwm_lift,1) if ciwm_lift is not None else "?")]

        # Headline bookends for the body text
        se_lift = _lookup("SE", MW_HEADLINE, "fsla", M_LEAD, "cfe_lift_pp_mean") or 0.0
        pl_lift = _lookup("PL", MW_HEADLINE, "fsla", M_LEAD, "cfe_lift_pp_mean") or 0.0
        out += [_macro("PecsLiftBookendSE", _fmt(se_lift, 1)),
                _macro("PecsLiftBookendPL", _fmt(pl_lift, 1))]

    # ── H1--H5 outcomes (always read if file present)
    out_path = ROOT / "data" / "m100" / "policy_matrix" / "HYPOTHESIS_OUTCOMES.json"
    if out_path.exists():
        h = json.loads(out_path.read_text())
        def _bool(k: str) -> str:
            try:
                return "PASS" if h[k].get("passed") else "INVESTIGATE"
            except KeyError:
                return "?"
        out += [_macro("PecsHone", _bool("H1_declared_tier_lift")),
                _macro("PecsHtwo", _bool("H2_nom_ic")),
                _macro("PecsHthr", _bool("H3_fairness")),
                _macro("PecsHfou", _bool("H4_swf_dominance")),
                _macro("PecsHfiv", _bool("H5_latency_monotone"))]
    else:
        missing.append("data/m100/policy_matrix/HYPOTHESIS_OUTCOMES.json")
        for k in ("PecsHone", "PecsHtwo", "PecsHthr", "PecsHfou", "PecsHfiv"):
            out += [_macro(k, "?")]

    return "".join(out), is_stub, missing


# ─────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────
def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--whpc-out", type=Path,
                     default=ROOT.parent / "papers" / "whpc2026" / "figs" / "results.tex")
    ap.add_argument("--pecs-out", type=Path,
                     default=ROOT.parent / "papers" / "pecs2026" / "figs" / "results.tex")
    args = ap.parse_args(argv)

    whpc_text, whpc_stub, whpc_missing = whpc_macros()
    pecs_text, pecs_stub, pecs_missing = pecs_macros()

    args.whpc_out.parent.mkdir(parents=True, exist_ok=True)
    args.pecs_out.parent.mkdir(parents=True, exist_ok=True)
    args.whpc_out.write_text(whpc_text)
    args.pecs_out.write_text(pecs_text)

    print(f"[macros] wrote {args.whpc_out.relative_to(ROOT.parent)}")
    if whpc_missing:
        print(f"[macros]   WARN: missing source files: {whpc_missing}",
                file=sys.stderr)
    print(f"[macros] wrote {args.pecs_out.relative_to(ROOT.parent)}")
    if pecs_stub:
        print(f"[macros]   NOTE: PECS macros derived from STUB data;",
                file=sys.stderr)
        print(f"[macros]         run scripts/multicountry/replay_country_sweep.py",
                file=sys.stderr)
        print(f"[macros]         and re-run this extractor for real numbers.",
                file=sys.stderr)
    if pecs_missing:
        print(f"[macros]   WARN: missing source files: {pecs_missing}",
                file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
