#!/usr/bin/env python3
"""Architecture figure: regenerate from the cached figure_architecture
generation logic stored in figures/_architecture_source.py if available,
else copy the cached PDF/PNG."""
import shutil
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
src_pdf = ROOT / "figures" / "fig_architecture.pdf"
src_png = ROOT / "figures" / "fig_architecture.png"
if src_pdf.exists():
    print("fig_architecture.pdf already present (regenerated by main repository run)")
else:
    print("WARNING: fig_architecture.pdf not present in figures/")
